export enum Patterns {
  USER_GET_ROLES = 'USER_GET_ROLES',
  CREATE_POST = 'POST_CREATE',
  GET_WITH_ID = 'POST_GET_WITH_ID',
  GET_WITH_SLUG = 'POST_GET_WITH_SLUG',
  GET_BY_USER = 'POST_GET_BY_USER',
  UPDATE = 'POST_UPDATE',
  DELETE = 'POST_DELETE',
}
